#!/bin/bash


cd ./ECE461_CLI

if [[ $1 == "help" ]]
then
    echo "possible commands: help install uninstall build clean run"
elif [[ $1 == "install" ]]
then
    chmod +x ../scripts/install_dependancies.sh
    ../scripts/install_dependancies.sh
elif [[ $1 == "uninstall" ]]
then
    chmod +x ../scripts/uninstall_dependancies.sh
    ../scripts/uninstall_dependancies.sh
elif [[ $1 == "build" ]]
then
    echo "hacking your computer..."
    # compile process 
    dotnet build
    echo "successfully hacked"
elif [[ $1 == "clean" ]]
then
    echo "Deleting your files..."
    dotnet clean
elif [[ $1 == "test" ]]
then
    cd ..
    dotnet test --collect:"XPlat Code Coverage"
elif [[ $1 == "logtest" ]]
then
    echo $LOG_FILE
else
    echo "thank you for your personal information!"
    echo "executing virus..."

    # run process
    dotnet run "$@"
fi


