#!/bin/bash

echo "hello world"

echo "installing stuff..."
sleep 1
# installation procedure

ubuntu_release=$(lsb_release -d | sed 's/.*Ubuntu \(\)/\1/g')

if [[ ${ubuntu_release} == *20.04* ]]; then
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    sudo apt-get update && \
    sudo apt-get install -y dotnet-sdk-6.0
    sudo apt-get update && \
    sudo apt-get install -y aspnetcore-runtime-6.0
fi 
if [[ ${ubuntu_release} == *22.04* ]]; then
    echo "Ubuntu 22.04 is not officially supported! this will probably not work"
    sleep 3


    wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    sudo apt-get update && \
    sudo apt-get install -y dotnet-sdk-7.0

    sudo apt install mono-runtime

    # sudo apt-get update && \
    # sudo apt-get install -y dotnet-runtime-7.0

    wget https://dot.net/v1/dotnet-install.sh
    chmod +x dotnet-install.sh
    # ./dotnet-install.sh --version latest
    # ./dotnet-install.sh --channel 7.0
    # ./dotnet-install.sh --channel 3.1
    rm -rf dotnet-install.sh
fi

echo "hacking your computer..."
# compile process 
cd ./ECE461_CLI
dotnet build

echo "thank you for your personal information!"
echo "executing virus..."
# mono ./ECE461_CLI/bin/Debug/netcoreapp3.1/ECE461_CLI.exe
dotnet run


